#region Using

using System;
using System.Collections.Generic;

#endregion

namespace NLib.Serial.ProtocolAnalyzer.Models
{
    /// <summary>
    /// Editable field definition for the Field Editor.
    /// </summary>
    public class FieldDefinition
    {
        #region Constructor

        /// <summary>
        /// Constructor.
        /// </summary>
        public FieldDefinition()
        {
            SampleValues = new List<string>();
            IsValid = true;
        }

        #endregion

        #region Public Properties

        /// <summary>
        /// Gets or sets the field position (0-based index).
        /// </summary>
        public int Position { get; set; }

        /// <summary>
        /// Gets or sets the auto-generated field name.
        /// </summary>
        public string AutoGeneratedName { get; set; }

        /// <summary>
        /// Gets or sets the user-defined field name.
        /// </summary>
        public string UserDefinedName { get; set; }

        /// <summary>
        /// Gets or sets the data type.
        /// </summary>
        public string DataType { get; set; }

        /// <summary>
        /// Gets or sets sample values from the data.
        /// </summary>
        public List<string> SampleValues { get; set; }

        /// <summary>
        /// Gets or sets the confidence score.
        /// </summary>
        public double Confidence { get; set; }

        /// <summary>
        /// Gets or sets the field description.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets whether the field is required.
        /// </summary>
        public bool IsRequired { get; set; }

        /// <summary>
        /// Gets or sets whether the field is constant.
        /// </summary>
        public bool IsConstant { get; set; }

        /// <summary>
        /// Gets or sets whether the current state is valid.
        /// </summary>
        public bool IsValid { get; set; }

        /// <summary>
        /// Gets or sets the unit of measurement (if applicable).
        /// </summary>
        public string Unit { get; set; }

        #endregion
    }
}
